import CodeBlock from '../components/CodeBlock'

export const toc = [
  { id: 'events', label: 'Events', level: 2 },
  { id: 'event-types', label: 'Event types', level: 3 },
  { id: 'properties', label: 'Properties', level: 3 },
  { id: 'identity', label: 'Identity & users', level: 2 },
  { id: 'sessions', label: 'Sessions', level: 2 },
  { id: 'schema', label: 'Schema & validation', level: 2 },
  { id: 'pipeline', label: 'Ingest pipeline', level: 2 },
]



export default function CoreConcepts() {
  return (
    <>
      <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '20px' }}>
        <span className="docs-badge docs-badge-orange">Getting Started</span>
      </div>

      <h1>Core Concepts</h1>
      <p style={{ fontSize: '17px', color: 'rgba(255,255,255,0.75)', lineHeight: 1.7, marginBottom: '32px' }}>
        Understanding how Advaita models events, users, and sessions will help you instrument your product correctly from day one.
      </p>

      <h2 id="events">Events</h2>
      <p>An <strong style={{ color: '#f6f6f1' }}>event</strong> is the fundamental unit of data in Advaita. Every event has three required fields and an optional properties object:</p>

      <table className="docs-prop-table">
        <thead><tr><th>Field</th><th>Type</th><th>Description</th></tr></thead>
        <tbody>
          <tr><td><code>event</code></td><td><code>string</code></td><td>The name of the action, e.g. <code>button_clicked</code> or <code>page_view</code>.</td></tr>
          <tr><td><code>user_id</code></td><td><code>string</code></td><td>The authenticated user's ID. Optional if the user is anonymous.</td></tr>
          <tr><td><code>anonymous_id</code></td><td><code>string</code></td><td>A device-level ID generated by the SDK for anonymous users.</td></tr>
          <tr><td><code>timestamp</code></td><td><code>ISO 8601</code></td><td>When the event occurred. Defaults to server receipt time if omitted.</td></tr>
          <tr><td><code>properties</code></td><td><code>object</code></td><td>Any JSON key-value pairs describing the event.</td></tr>
        </tbody>
      </table>

      <h3 id="event-types">Event types</h3>
      <p>Advaita recognises three built-in event types that receive special treatment in the pipeline:</p>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '1px', background: 'rgba(255,255,255,0.07)', borderRadius: '10px', overflow: 'hidden', marginBottom: '20px' }}>
        {[
          { badge: 'track', color: '#f5820a', title: 'Track', desc: 'A user action. Name it with a verb + noun in snake_case: button_clicked, checkout_completed, feature_used.' },
          { badge: 'page', color: '#a78bfa', title: 'Page', desc: 'A page or screen view. Automatically captures URL, referrer, and title in web SDKs.' },
          { badge: 'identify', color: '#4a9e1a', title: 'Identify', desc: 'Links an anonymous_id to a known user_id and attaches persistent user traits.' },
        ].map(item => (
          <div key={item.badge} style={{ padding: '16px 20px', background: '#0f0f0f', display: 'flex', gap: '14px', alignItems: 'flex-start' }}>
            <span style={{ padding: '3px 8px', borderRadius: '5px', fontSize: '11px', fontWeight: '700', fontFamily: 'monospace', background: `${item.color}18`, border: `1px solid ${item.color}30`, color: item.color, flexShrink: 0 }}>{item.badge}()</span>
            <div>
              <strong style={{ fontSize: '14px', color: '#f6f6f1', display: 'block', marginBottom: '3px' }}>{item.title}</strong>
              <p style={{ margin: 0, fontSize: '13px', color: 'rgba(255,255,255,0.55)', lineHeight: 1.6 }}>{item.desc}</p>
            </div>
          </div>
        ))}
      </div>

      <h3 id="properties">Properties</h3>
      <p>Properties are free-form key-value pairs attached to any event. Advaita auto-collects a set of context properties and merges them with your custom ones:</p>
      <CodeBlock>{`{
  // Your custom properties
  "plan": "pro",
  "button_id": "upgrade_cta",

  // Auto-collected context
  "$os": "macOS",
  "$browser": "Chrome 124",
  "$referrer": "https://google.com",
  "$session_id": "sess_a8f2k1",
  "$lib": "advaita-js-sdk@1.4.2"
}`}</CodeBlock>

      <h2 id="identity">Identity &amp; users</h2>
      <p>Advaita uses a two-stage identity model:</p>
      <ul>
        <li><strong style={{ color: '#f6f6f1' }}>Anonymous ID</strong> — Generated by the SDK on first load and persisted in local storage. Every event carries this ID so pre-login sessions are fully captured.</li>
        <li><strong style={{ color: '#f6f6f1' }}>User ID</strong> — Your application's user identifier. Set this by calling <code>identify()</code> on login. Advaita merges the anonymous session history into the identified profile.</li>
      </ul>

      <div className="docs-callout docs-callout-info">
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none" style={{ flexShrink: 0, marginTop: '1px' }}><circle cx="8" cy="8" r="6.5" stroke="#a78bfa" strokeWidth="1.4"/><path d="M8 7v4M8 5v.5" stroke="#a78bfa" strokeWidth="1.5" strokeLinecap="round"/></svg>
        <p>Always call <code>identify()</code> after a successful login, not before. The SDK will alias the anonymous session to the user ID automatically.</p>
      </div>

      <h2 id="sessions">Sessions</h2>
      <p>A session begins when a user first loads your app and ends after <strong style={{ color: '#f6f6f1' }}>30 minutes of inactivity</strong> (configurable). Sessions are tracked automatically — you don't need to call any session methods.</p>
      <p>Each session carries a unique <code>$session_id</code> so you can reconstruct the full user journey, measure session depth, and analyse drop-off by session number.</p>

      <h2 id="schema">Schema &amp; validation</h2>
      <p>Advaita has an optional schema registry. You can define expected properties and their types for any event name. When a captured event violates the schema, it is flagged in the <strong style={{ color: '#f6f6f1' }}>Data Interface → Schema Health</strong> view but is still stored — nothing is dropped.</p>
      <p>Schema enforcement modes:</p>
      <ul>
        <li><strong style={{ color: '#f6f6f1' }}>Observe</strong> (default) — Capture everything, flag violations as warnings.</li>
        <li><strong style={{ color: '#f6f6f1' }}>Warn</strong> — Store the event, alert the team, and surface in the dashboard.</li>
        <li><strong style={{ color: '#f6f6f1' }}>Strict</strong> — Reject events that violate required fields. Not recommended for production without testing.</li>
      </ul>

      <h2 id="pipeline">Ingest pipeline</h2>
      <p>Every event passes through the following stages before it is available for analysis:</p>

      <ol>
        <li><strong style={{ color: '#f6f6f1' }}>Receipt</strong> — The ingest API acknowledges the event and assigns a server timestamp if none is provided.</li>
        <li><strong style={{ color: '#f6f6f1' }}>Enrichment</strong> — IP geolocation, device parsing, and session stitching are applied.</li>
        <li><strong style={{ color: '#f6f6f1' }}>Schema validation</strong> — The event is checked against your schema registry. Violations are flagged.</li>
        <li><strong style={{ color: '#f6f6f1' }}>Storage</strong> — The event is written to your project's clickstream store, typically within 200ms of receipt.</li>
        <li><strong style={{ color: '#f6f6f1' }}>Indexing</strong> — Event properties are indexed for fast funnel and cohort queries.</li>
      </ol>
    </>
  )
}
